# Generated by Django 5.2.4 on 2025-08-07 09:20

import Tracker.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите название упражнения",
                        max_length=250,
                        verbose_name="Название упражнения",
                    ),
                ),
                (
                    "muscle_group",
                    models.CharField(
                        choices=[
                            ("chest", "Грудь"),
                            ("back", "Спина"),
                            ("arms", "Руки"),
                            ("legs", "Ноги"),
                            ("core", "Пресс"),
                            ("cardio", "Кардио"),
                        ],
                        help_text="Выберите необходимую группу мышц",
                        max_length=100,
                        verbose_name="Группа мышц",
                    ),
                ),
            ],
            options={
                "verbose_name": "Упражнение",
                "verbose_name_plural": "Упражнения",
            },
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата тренировки",
                        verbose_name="Дата тренировки",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Заметки о тренировки",
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тренировка",
                "verbose_name_plural": "Тренировки",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Set",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        default=0,
                        help_text="Вес в кг",
                        validators=[Tracker.validators.validate_weight],
                        verbose_name="Вес",
                    ),
                ),
                (
                    "reps",
                    models.PositiveIntegerField(
                        help_text="Количество повторений",
                        validators=[Tracker.validators.validate_reps],
                        verbose_name="Количество повторений",
                    ),
                ),
                (
                    "rest_after_set",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Отдых после подхода в секундах",
                        null=True,
                        verbose_name="Отдых после подхода",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="Tracker.exercise",
                        verbose_name="Упражнение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подход",
                "verbose_name_plural": "Подходы",
            },
        ),
    ]
