# Generated by Django 5.2.4 on 2025-08-12 08:49

import Tracker.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tracker", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="set",
            name="reps",
            field=models.PositiveIntegerField(
                validators=[Tracker.validators.validate_reps],
                verbose_name="Количество повторений",
            ),
        ),
    ]
