# Generated by Django 5.2.4 on 2025-08-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tracker", "0004_alter_workout_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Заметка о тренировке",
                null=True,
                verbose_name="Комментарий",
            ),
        ),
    ]
