# Generated by Django 5.2.4 on 2025-08-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tracker", "0005_alter_workout_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="set",
            name="icon",
            field=models.CharField(blank=True, max_length=50, verbose_name="Иконка"),
        ),
    ]
