# Generated by Django 5.2.4 on 2025-09-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tracker", "0007_workoutevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutevent",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
