# Generated by Django 5.2.4 on 2025-09-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tracker", "0008_workoutevent_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("default", "Запланирована"),
                    ("success", "Прошла успешно"),
                    ("cancelled", "Отменилась"),
                ],
                default="default",
                max_length=20,
            ),
        ),
    ]
