# Generated by Django 5.2.4 on 2025-09-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tracker", "0009_workoutevent_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutevent",
            name="start",
            field=models.DateTimeField(
                db_index=True, verbose_name="Полная дата + время начала"
            ),
        ),
    ]
